[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev --no-interaction"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public router.php"
